name: CI/CD .Net Core

on: 
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      build_config: Release
    steps:
    - uses: actions/checkout@v2.4.2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.1.0
    
    - name: Install dotnet tools
      run: dotnet tool restore
      
    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration $build_config
    
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration $build_config
    
    - name: Publish site
      working-directory: ./src/Web
      run: dotnet publish -c $build_config -o ../../web_publish
    
    - name: Catalog SQL Script
      run: dotnet ef migrations script -c catalogcontext -i -p ./src/Infrastructure/Infrastructure.csproj -s ./src/Web/Web.csproj -o ./scripts/catalog.sql
    
    - name: Identity SQL Script
      run: dotnet ef migrations script -c appidentitydbcontext  -i -p ./src/Infrastructure/Infrastructure.csproj -s ./src/Web/Web.csproj -o ./scripts/identity.sql
    
    - name: Upload scripts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: sql_scripts
        path: ./scripts
    
    - name: Upload site
      uses: actions/upload-artifact@v3.1.0
      with:
        name: web_site
        path: ./web_publish
    
    - name: Upload ARM
      uses: actions/upload-artifact@v3.1.0
      with:
        name: arm_template
        path: arm
    
  deploy_dev:
    needs: build    
    uses: ./.github/templates/template-deploy.yml@main
    with:
      environment-to-deploy: dev
      site-name: dotnet2022dev
      sql-name: dotnet22devsql
      resource-group: DotNet2022_Dev_RG
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      CONNSTRING_JSON: ${{ secrets.CONNSTRING_JSON }}
      CATALOG_DB_CONNSTRING: ${{ secrets.CATALOG_DB_CONNSTRING }}
      IDENTITY_DB_CONNSTRING: ${{ secrets.IDENTITY_DB_CONNSTRING }}

  deploy_pro:
    needs: deploy_dev
    uses: ./.github/templates/template-deploy.yml@main
    with:
      environment-to-deploy: pro
      site-name: dotnet2022pro
      sql-name: dotnet22prosql
      resource-group: DotNet2022_Pro_RG
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      CONNSTRING_JSON: ${{ secrets.CONNSTRING_JSON }}
      CATALOG_DB_CONNSTRING: ${{ secrets.CATALOG_DB_CONNSTRING }}
      IDENTITY_DB_CONNSTRING: ${{ secrets.IDENTITY_DB_CONNSTRING }}